# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61617f45c96835c5f8ddbeca366def78ce0a4f394bf4511a8ba6b0b28296854875bd3c8446070caaf5dc0918153387a42d428d251fd136de546a4d11f1338a0e

test:
  secret_key_base: 55651d8137d4b28074c10e052c266335b3624326d5e32e2a5a1628870d0e55d2c4c4b0af81c096400b6b4f020bd376db34b8836340d4332bf6030ed64755cd21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
